template = "https://github.com/giellalt/template-lang-und"
rev_id = 337
template_sha = "1c2fffaa917a9c6f340d9887d554609eb561ade6"

[replacements]
__GLOTTOLOG_ID__ = "uppe1275"
__REPO__ = "lang-tku"
__UND2C__ = "tku"
__UNDEFINED__ = "Upper Necaxa Totonac"
__UND__ = "tku"
