[package]
name = "tku"
human_name = "Upper Necaxa Totonac"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.tku]
filename = "tku-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-tku"
platform = "windows"
uuid = "C06B02FF-6349-4A62-83B8-D07068489B88"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.tku"
package = "speller-tku"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-tku-mso"
platform = "windows"
uuid = "6A910FE7-2F18-47A0-9DE0-7312DCF81314"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-tku"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
